
name: SonarCloud analysis

on:
  push:
  workflow_dispatch:

jobs:
  SAST:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        with:
          args:
            -Dsonar.projectKey="DevSecOps-roth_laboratorio-final"
            -Dsonar.organization="devsecops-roth"
          projectBaseDir: .
  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install
      
      - name: Instalar Snyk
        run: npm install -g snyk
        
      - name: Análisis con Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
          
      - name: Ejecuta Snyk
        run: |
          snyk test --all-projects --json > snyk-results.json || true
          
      - name: Subir resultados de Snyk
        uses: actions/upload-artifact@v3
        with:
          name: snyk-results
          path: snyk-results.json
          
      - name: Verificar Vulnerabilidades
        run: |
          if jq '.[] | select(.vulnerabilities | length > 0)' snyk-results.json; then
            echo "Se detectaron vulnerabilidades."
            exit 1
          else
            echo "Sin vulnerabilidades detectadas."
          fi
